--CREATE DATABASE IF NOT EXISTS storeDB;
--DROP DATABASE storeDB;
--CREATE DATABASE IF NOT EXISTS storeDB TEMPLATE template0;
SELECT 'CREATE DATABASE storeDB TEMPLATE template0' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'storeDB');
CREATE SCHEMA IF NOT EXISTS PUBLIC;

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  uuid UUID PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  name VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL
);
