--CREATE DATABASE IF NOT EXISTS storeDB;
--DROP DATABASE storeDB;
--CREATE DATABASE IF NOT EXISTS storeDB TEMPLATE template0;
SELECT 'CREATE DATABASE storeDB TEMPLATE template0' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'storeDB');
CREATE SCHEMA IF NOT EXISTS PUBLIC;

DROP TABLE IF EXISTS SALEDETAILS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  uuid UUID PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  name VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL
);

--CREATE SEQUENCE ORDERS_SEQ;
CREATE TABLE ORDERS (
    id BIGINT PRIMARY KEY DEFAULT NEXTVAL('ORDERS_SEQ'),
    name VARCHAR(100),
    description VARCHAR(200),
    customer_uuid UUID REFERENCES customer(uuid),
    totalOrder DECIMAL(18, 2)
);

--CREATE SEQUENCE SALEDETAILS_SEQ;
CREATE TABLE SALEDETAILS (
    id BIGINT PRIMARY KEY DEFAULT NEXTVAL('SALEDETAILS_SEQ'),
    sku VARCHAR(100),
    quantity BIGINT,
    unitPrice DECIMAL(18, 2),
    totalPrice DECIMAL(18, 2),
    discountAmount DECIMAL(18, 2),
    order_id BIGINT REFERENCES orders(id)
);
